export { default as VerificationEmailSent } from "./VerificationEmailSent"
export { default as ResetPassword } from "./ResetPassword"
export { default as Register } from "./Register"
export { default as Login } from "./Login"
export { default as ForgotPassword } from "./ForgotPassword"
export { default as EmailVerified } from "./EmailVerified"
export { default as Auth } from "./Auth"
